---
- name: Ensure printer_data E3CNC macros directory exists
  ansible.builtin.file:
    path: '{{ printer_data.E3CNC_dir }}/macros'
    state: directory
    mode: '0755'

- name: Deploy wcs_macros.cfg
  ansible.builtin.copy:
    src: '{{ repo.dest }}/E3CNC/macros/wcs_macros.cfg'
    dest: '{{ printer_data.E3CNC_dir }}/macros/wcs_macros.cfg'
    mode: '0644'
    remote_src: true

- name: Deploy e3cnc_macros.cfg
  ansible.builtin.copy:
    src: '{{ repo.dest }}/E3CNC/E3CNC/macros/e3cnc_macros.cfg'
    dest: '{{ printer_data.E3CNC_dir }}/macros/e3cnc_macros.cfg'
    mode: '0644'
    remote_src: true

- name: Deploy theme.json
  ansible.builtin.copy:
    src: '{{ repo.dest }}/E3CNC/E3CNC/theme.json'
    dest: '{{ printer_data.E3CNC_dir }}/theme.json'
    mode: '0644'
    remote_src: true
