---
repo:
  url: https://github.com/isaaceliape/mainsail-cnc.git
  dest: '{{ ansible_env.HOME }}/mainsail-cnc'
  branch: main

frontend:
  web_root: '{{ ansible_env.HOME }}/mainsail'

agent:
  vender_dir: '{{ ansible_env.HOME }}/moonraker/moonraker/components'
  source_dir: '{{ repo.dest }}/E3CNC/moonraker-cnc-agent'

klipper:
  extras_dir: '{{ ansible_env.HOME }}/klipper/klippy/extras'

printer_data:
  config_dir: '{{ ansible_env.HOME }}/printer_data/config'
  E3CNC_dir: '{{ printer_data.config_dir }}/E3CNC'
  scripts_dir: '{{ ansible_env.HOME }}/printer_data/scripts'
  macros_dir: '{{ ansible_env.HOME }}/printer_data/config/macros'

moonraker_conf: '{{ printer_data.config_dir }}/moonraker.conf'
